### PR TITLE
Stripping headers from .md files with Lua

### PR DESCRIPTION
**Pull request by tonyquicktech**
So I've got the code working on my local machine, but I'm not sure why its unable to resolve action actions/setup-lua. 

Also, the input is hard coded into the script at the moment. Given my very limited knowledge of this language, it might take me sometime to figure out a sort of dynamic solution. Any input would be greatly appreciated from both @bountonw and @mattleff

### CODE REVIEW

**Comment by bountonw** [comment]
We will not be calling this directly from a workflow. It will be called by whatever the workflow is calling. It will have a parent script.

* `makeTXT.lua`
* `makePDF.lua`
* `makeHTML.lua`
* `makeEPUP.lua`
* etc.

Or whatever they end up being named will all call this function. But there is no need to write it 5-6 times. Having it in it's separate file makes it useful for all of the export scripts as they all need to strip out the subheadings.

**Comment by tonyquicktech** [comment]
Quick clarification - the script is only needed for stripping the headers - not for outputting to a file, correct? If that's the case, then I can go with an earlier version of my code. Also, do the ### headers need to be stripped as well, or just the three hashes stripped with the header text left intact?

**Comment by bountonw** [comment]
@mattleff Can you review this?

**Review by mattleff — COMMENTED** [review]
Sorry I haven't been able to get time to test this yet. Two questions:

1. Does this strip all blank lines? (line 5, case 2, I think so, right?) Do we want it to?
2. I appreciate using `io.lines` to avoid loading the whole file into memory, but it does require that the input is a file instead of a string. Idk how things work with Lua but I had envisioned sort of a pipeline that applied filters in preparing source .md's for output, and in that case we would either have to write temporary files with the contents of the previous operations, or use string input for each function rather than file names. Thoughts?

**Comment by bountonw** [comment]
My basic point is that a function that is used on multiple processes should only be written once. That we if it needs updating, we only have to update one thing. We will be adding html export whenever the pdf exports are working. Etc. The paragraph headers are only there to help in navigation on GitHub but are in the way when sharing the files. So they need stripped along with the blank line that immediately follows them.

Having reusable functions should help to save us from spaghetti code.

**Comment by tonyquicktech** [comment]
> Sorry I haven't been able to get time to test this yet. Two questions:
> 
> 1. Does this strip all blank lines? (line 5, case 2, I think so, right?) Do we want it to?
> 2. I appreciate using `io.lines` to avoid loading the whole file into memory, but it does require that the input is a file instead of a string. Idk how things work with Lua but I had envisioned sort of a pipeline that applied filters in preparing source .md's for output, and in that case we would either have to write temporary files with the contents of the previous operations, or use string input for each function rather than file names. Thoughts?

To answer question 1, yes, it does strip all of the added spaces (all of the blank spaces were added by me to start with - in the source directory that is) so I think it is probably good to have those removed when sharing, as I assume the proper line width specs are already built into the yaml?

As for question 2 - yes, it was made with large files in mind - would there be a benefit to strings over the file? I'm no expert in Lua, but I think we can modify this code as necessary once you have the bigger process setup? Perhaps it might be useful to have a flowchart so we can all picture the exact export process, all of its steps, and the scripts necessary for each. With that, we should then be able to figure out how best to modify the code so as to remove redundancies or bloated operations. Just a thought, as I find that diagramming first usually helps with unforeseen issues down the road.

**Comment by mattleff** [comment]
@tonyquicktech Thanks for the work and discussion on this PR. It turns out that the Pandoc Lua filters are structured differently, so I reimplemented this in #176. That uses the Lua Pandoc API to define a filtering function for the Pandoc AST. There are some examples [here](https://pandoc.org/lua-filters.html#examples). I'm still trying to wrap my head around how all of these should work, so feel free to suggest improvements.

**Pull request closed without merging**
