### PR TITLE
Add a couple linting rules

### PR DESCRIPTION
**Pull request by mattleff**
Refs #151. This PR addresses rule 1 & 2. Rule 3 is actually already there ([here](https://github.com/bountonw/translate/blob/0844a8e62a2c1d13b9b19f95da6e947c165dae74/.tooling/markdownlint/custom-formatting.js#L17-L19)). Rule 4 (about Thai vs. Lao characters) could be addressed using the forbidden terms files (by adding each letter in a given language to the file for that language), but maybe there's a better way?

### CODE REVIEW

**Comment by bountonw** [comment]
@mattleff Are these rules working? I have been coming across these issues almost daily. Or are they only working on some files? Except for the parenthesis rule which shouldn't apply to edit and raw folders, these other rules should apply to the raw and edit folders too.

**Comment by mattleff** [comment]
@bountonw They are currently only applying to the `03_public` folders. I can change them to apply to `01_raw` and `02_edit` as well. Should any of these rules apply to `00_source` folders?

**Comment by mattleff** [comment]
@bountonw I've made most of the rules apply to the raw/edit folders also and there's a number of linting failures now. Let me know if I should turn off any of these rules for raw/edit, or if we want to fix all these errors.

**Comment by bountonw** [comment]
Looks good. I will work on fixing the linting mistakes that are being flagged.

**Review by bountonw — COMMENTED** [review]
If something applies to all languages, why is it written in multiple files? (We will be adding Mien whenever the dust settles so that SC chapter 1 can be reviewed.)

**Comment by mattleff** [comment]
> If something applies to all languages, why is it written in multiple files? (We will be adding Mien whenever the dust settles so that SC chapter 1 can be reviewed.)

@bountonw The only rule that should be duplicated in multiple files is the `missing space after closing curly quotes` rule. The reason I duplicated this rule is that it should not be applied to the English source files (since `it’s`, `their’s`, etc. are proper in English). If we decide to exclude the English source files in `/source/**` from all these rules then I could move it back into `custom-formatting.js` to apply to all languages. We can DRY these rules out more as we add more languages. It would be easy to have a shared rules file with common regexes that we can import and apply to multiple languages from one common definition point. That makes more sense as we have more languages.

**Comment by bountonw** [comment]
@mattleff I am still working on fixing the issues flagged by the linting rules. The double spacing rule should not apply to the two files in `/th/MB/assets` folder that are being flagged. Since these files should be static, perhaps we can just ignore the entire folder. However, if a more granular solution is available, that is good too. 

Merging will be blocked until these files are not linted, since the extra spaces are probably valid. Another solution would be to rename the two files to `.txt`.

**Review by bountonw — APPROVED** [review]

**Pull request merged**
