### PR TITLE
Move some lints earlier

### PR DESCRIPTION
**Pull request by mattleff**
Refs https://github.com/bountonw/translate-tooling/pull/55.

### CODE REVIEW

**Comment by mattleff** [comment]
@bountonw I've moved up the linting from public folder to edit + public folder. However, just looking at the lint failures, I'm not sure if this really what we want. Let me know if this looks ok and you want to deal with these errors at the edit phase.

**Comment by bountonw** [comment]
You are right! There are a lot more things showing up that shouldn't. I have reviewed the changed files and the linked  changes in tooling, but don't understand what is going on. It seems that more than just smart quotes and maiyamuk are effected. (I don't any changes to what ever is happening with the Lao files. So we shouldn't get any Lao files in this update.) Also, parentheses should not be effected. I still need to be able to (((stack parentheses))) in the edit files.

**Comment by bountonw** [comment]
@mattleff What is the status of this? The week at the evangelistic meetings has deleted some of my memory. I think there is an unresolved comment, but I could be mistaken.

**Comment by mattleff** [comment]
@bountonw This is still in my court. I need to update the tooling PR to change only the Thai rules to apply to files in edit. I'll try to do it later today.

**Comment by mattleff** [comment]
@bountonw Ok, I think this looks better. Let me know if it seems right to you.

**Comment by bountonw** [comment]
@mattleff if an ellipsis follows a mayamok then there shouldn't be a space. Other than that, we can batch add spaces to these.

**Comment by mattleff** [comment]
@bountonw See if these changes look alright.

**Comment by mattleff** [comment]
@bountonw I think this is good to merge if it looks good to you.

**Review by bountonw — APPROVED** [review]

**Pull request merged**
