### PR TITLE
Edit LBF chapters 22 – 23

### PR DESCRIPTION
**Pull request by bountonw**
* Update forbidden words and fix linting errors caught.

### CODE REVIEW

**Comment by bountonw** [comment]
@mattleff LBF22 was failing because of the new `<` way of marking block quotes. I found a work around by adding another paragraph tag. 

Also, I don't know if the blank line is supposed to be marked that way of not.

**Comment by bountonw** [comment]
@mattleff This is ready to review.

**Review by mattleff — APPROVED** [review]

**Comment by mattleff** [comment]
@bountonw I'll check on LBF22 and try to improve the linting.

**Comment by bountonw** [comment]
@mattleff The ICML workflow should only run when files are changed or added to the `LBF/03_public` folder.

**Comment by mattleff** [comment]
> @mattleff The ICML workflow should only run when files are changed or added to the `LBF/03_public` folder.

@bountonw Yup, it's [setup that way](https://github.com/bountonw/translate/blob/0d4f10a88d87a013ec9d153111871e97915564d2/.github/workflows/generate-lbf-icml.yml#L6). This PR touched one file in that folder:

https://github.com/bountonw/translate/pull/244/files#diff-cc4a432358247f9f3eaba10eda84655ca994dba9bb418726a7120611c36aedb0

**Comment by bountonw** [comment]
@mattleff changes to forbidden words shouldn't trigger new builds as only when the actual translation files change should they be built.

**Pull request merged**
