### PR TITLE
Edit LBF chapters 24–26

### PR DESCRIPTION
**Pull request by bountonw**
* Ready to move to the public folder for typesetting

### CODE REVIEW

**Comment by mattleff** [comment]
@bountonw Sorry, I made merge conflicts for you with #243. I had to fix the lint errors from https://github.com/bountonw/translate-tooling/pull/10. When you merge in main on this branch just take your changes on LBF25 and let lint run when you push.

**Comment by bountonw** [comment]
@mattleff Ready to review

**Review by mattleff — APPROVED** [review]

**Comment by bountonw** [comment]
@mattleff This is blocked by a failing workflow that I don't understand.

**Comment by mattleff** [comment]
@bountonw I think the failure was because of the colon in the yaml value. Any rate, it's fixed with efe1a4c5b9b36aa33166bb241750010876baa6b1.

**Pull request merged**
