### PR TITLE
Support forbidden word breaks

### PR DESCRIPTION
**Pull request by mattleff**
Applies forbidden word breaks to ICML generation and supports forbidden word break strings with spaces and numbers

### CODE REVIEW

**Comment by mattleff** [comment]
[LBF ICMLs with Forbidden Breaks.zip](https://github.com/bountonw/translate/files/15058616/LBF.ICMLs.with.Forbidden.Breaks.zip)

@kenton-r I've attached here a set of LBF ICMLs with an initial forbidden word breaks style applied. The list of actual words still needs to be reviewed by Brian. Let me know if you want a different character style name and I can easily change it. If there's anything else amiss let me know.

**Comment by kenton-r** [comment]
[Template_1b_LbF.pdf](https://github.com/bountonw/translate/files/15069989/Template_1b_LbF.pdf)

So this removes the grep styling in InDesign for the Bible book names. It looks like it is working well. 

But I was wondering if the script is able to hand "1 Peter"? We would still need Peter as a word too.

**Comment by mattleff** [comment]
@kenton-r Ok, try these files: [LBF.zip](https://github.com/bountonw/translate/files/15070552/LBF.zip)

**Comment by kenton-r** [comment]
[Template_1c_LbF.pdf](https://github.com/bountonw/translate/files/15070701/Template_1c_LbF.pdf)

Thank you!
This works well.

**Review by bountonw — APPROVED** [review]

**Pull request merged**
