### PR TITLE
Import MB Thai

### PR DESCRIPTION
**Pull request by bountonw**
The .text files are the source files for the version of the Thai translation of Thoughts from the Mount of Blessings by Ellen White published 2023. They are imported "as is."

### CODE REVIEW

**Comment by bountonw** [comment]
@hsteck1844 Can you look at the *000.text files and see if these are something that we should retain?

**Comment by hsteck1844** [comment]
> @hsteck1844 Can you look at the *000.text files and see if these are something that we should retain? 

I think the files you are talking about apply only to the credits page, right? I apologize, I'm not sure how closely these text files represent the final product. (In other words, I'm not sure how many changes/corrections I made to the inDesign file after importing the text. I hope the text matches, but can't promise from that long ago.

**Comment by bountonw** [comment]
@hsteck1844 

Yes, the credits page. Do we need these for any reason or should we just delete them? 

@mattleff if we keep them, where do we put them. They are not really part of the translation texts but are part of the book.

**Comment by mattleff** [comment]
@bountonw I guess I would think of them as assets (things used in the book, but not the text of the book).

**Pull request merged**
