### PR TITLE
Refactor markdown

### PR DESCRIPTION
**Pull request by bountonw**
* Add blank line after yaml header
* Promote paragraph to ## level subheader
* Demote subtitles to ### level and nest them under their respective paragraphs
* Standardize spacing after "##" and "###" to single space

### CODE REVIEW

**Comment by bountonw** [comment]
@mattleff 

Can you review this to make sure that I didn't do something unintentional and then squash-merge if it is ok?

**Comment by bountonw** [comment]
Actually, there is one more thing that needs to be done. But I don't know how to do it. I want to delete multiple spaces inside of text without effecting the yaml.

**Comment by bountonw** [comment]
@mattleff I have merged this pull request. Before I delete the branch, I have a question. Why does github show the commit as having 3 authors? And who is the mysterious third author?

**Comment by mattleff** [comment]
@bountonw If you look at the [commit](https://github.com/bountonw/translate/commit/60128923f7b357f151f1662c64cbfc9c3f8f63ef) it lists the coauthors as me and you, each with our email addresses. My guess is that the email listed for you isn't the same as in your GitHub account ([here](https://github.com/settings/emails)). If it is not the same you can add an alternate email to your GitHub account that will be used to associate commits from that email with your GitHub user. If it is the same, I'm not sure right off why it would list three users.

**Comment by bountonw** [comment]
@mattleff Thank you!

**Pull request merged**
