### PR TITLE
Attempt to fix pdf builds

### PR DESCRIPTION
**Pull request by mattleff**
This PR looks more complicated than it is since I needed to merge main to this branch so that I could get those changes for my fixes.

### CODE REVIEW

**Comment by bountonw** [comment]
@mattleff will I lose file history?

**Comment by mattleff** [comment]
> @mattleff will I lose file history?

@bountonw I don't think so. I think if this fixes the Latex PDFs enough to merge that branch in it might be a good idea to merge it and then keep fixing stuff.

**Comment by mattleff** [comment]
@bountonw The actual changes on this PR is https://github.com/bountonw/translate/pull/155/commits/2cadf3c8e9cd1d88ffe3b8bc4dd9faef04453f44. If that looks good, the rest is just changes from main.

**Review by bountonw — COMMENTED** [review]
It is important to me that I don't lose file history of the translation files. Even more importantly is that I don't lose three weeks of editing work with files being overwritten. If this is a risk, I recommend taking the files that are changed and put them into a clean PR. 

This PR is showing that files are deleted and other files are added. (I moved these files and in the main branch they are shown as renamed.)

Although Paulo helped in making the origin markdown file, I don't know that we should consider him the publisher.

**Pull request closed without merging**
