### PR TITLE
Add Foreword and text of copyright page

### PR DESCRIPTION
**Pull request by bountonw**

### CODE REVIEW

**Comment by bountonw** [comment]
@mattleff We will need an exception on this to not validate for paragraph tags.

**Comment by bountonw** [comment]
English Back translation:

A.D. 1888 was a very important year in Seventh-day Adventist History. There was a pastor's meeting from October 10–16 followed by a General Conference session from October 17 to November 4 in Minneapolis, MN. Elder E J Waggoner and Elder A T Jones presented on Righteousness by faith. Ellen G White called this teaching, "A most precious message." In 1892 she wrote, "...the loud cry of the third angel has already begun in the revelation of the righteousness of Christ.... This is the beginning of the light of the angel whose glory shall fill the whole earth." (See Revelation 18.1) (RH November 22, 1892)

It is unfortunate that no one recorded the sermons of Jones and Waggoner in 1888, however we can ascertain what they taught from their various articles that write subsequently. This book is a collection of articles published by Jones and Waggoner between 1890–1896. Most of the articles are from the magazine The Present Truth, while some of the articles are from other church publications, namely, The Signs of the Times, The Advent Review and Sabbath Herald, and The Bible Echo.

It is the hope of the publishers that the book Living by Faith will .....

**Comment by kenton-r** [comment]
สงวนลิขสิทธ์ิ © 2022 สำานักพิมพ์ข่าวประเสริฐ

สัญญาอนุญาตครีเอทีฟคอมมอนส์ แสดงท่ีมา-ไม่ดัดแปลง 4.0 
International (CC BY-ND 4.0) (https://creativecommons.org/licenses/by-nd/4.0/)

แปลจากหนังสือ : Living By Faith

ผู้แปล : Brian Wilson 

จัดเข้าเล่มและออกแบบปก : Kenton Rogers, Publishing Light Press Asia

การประมวลผลข้อความแบบดิจิทัล : Matthew Leffler

จัดพิมพ์ : สำานักพิมพ์ข่าวประเสริฐ

12 ซอยปรีดี พนมยงค์ 37 ถนนสุขุมวิท 71
แขวงคลองตันเหนือ เขตวัฒนา กรุงเทพมหานคร 10110

พระคัมภีร์ท่ีใช้เป็นหลักคือ

- พระคริสตธรรมคัมภีร์ฉบับมาตรฐาน (THSV) สงวนลิขสิทธ์ิ © 2011 โดยสมาคมพระคริสตธรรมไทย ใช้โดยได้รับอนุญาต

ส่วนพระคัมภีร์ฉบับแปลไทยเล่มอ่ืนได้แก่

- พระคัมภีร์ภาษาไทยฉบับคิงเจมส์ (TKJV) สงวนลิขสิทธ์ิ © 2003 Philip Pope
- พระคริสตธรรมคัมภีร์ ฉบับอมตธรรมร่วมสมัย (TNCV) Thai Holy Bible, Thai New Contemporary Version Copyright © 2001, 2007, 2011 by Biblica Thailand. All rights reserved. สงวนลิขสิทธิ์โดยองค์การอมตธรรม ใช้โดยได้รับอนุญาตจากองค์การอมตธรรม
- พระคริสตธรรมคัมภีร์ ฉบับ ค.ศ. 1971 (TH1971)
- พระคริสตธรรมคัมภีร์ ฉบับ ค.ศ. 1940 (TH1940)

พิมพ์ในประเทศไทย

ข้อมูลทางบรรณานุกรมของสำานักหอสมุดแห่งชาติ
National Library of Thailand Cataloging in Publication Data

**Comment by kenton-r** [comment]
There are still some questions to be answered with the copyright page. Who is going to hold the copyright. Will it be the Thai Mission or Mike or Love for Asia? Because it is creative commons the distribution is not prohibited, but it changes were wanting to be made to the book then the copyright hold would have to give written permission.

Also we need to indicate that it is only the book text that is under creative commons. The cover is not under creative commons.
so we could say something like:
Book Text. All Right Reserved © 2024 Mike Kiers.

Also which other versions of the Bible do we need to include.

**Comment by bountonw** [comment]
@mattleff I don't understand the linting errors of the copyright text.

@kenton-r We have listed TAM as the publishers and copyright holder. Is this what we want?

**Comment by bountonw** [comment]
@mattleff @kenton-r Or would it be better to have the copyright page as a `.txt` file. If we did that, would we lose anything by way of formatting, or is the page typeset manually anyway?

**Comment by mattleff** [comment]
@bountonw I don't think we need either of those lint rules, so I'll turn them off.

**Review by mattleff — APPROVED** [review]
Ok, I'm just reviewing this because when I pushed the lint fix on the branch it now needs my review since @bountonw made the PR

**Comment by bountonw** [comment]
I'm still working on the text of the foreword and am not ready to merge yet.

**Comment by bountonw** [comment]
@mattleff Can you update the .tooling for this PR to incorporate the latest changes?

**Comment by mattleff** [comment]
@bountonw Submodule is updated. 1 lint error.

**Comment by bountonw** [comment]
Fixed. This was hard to spot. But each สำ word had an extra า. Now we are protected from this problem.

**Pull request merged**
