### PR TITLE
Generate PDFs with LaTeX

### PR DESCRIPTION
**Pull request by mattleff**
This adds basic support for generating PDFs with LaTeX running in GitHub Actions. `draftall.sh` is still the main entry point, and basically the only changes to the old scripts are related to directory paths and markdown extension (`.text` -> `.md`). With this PR artifacts are generated on every commit, but we could narrow that to only commits touching `.tooling/latex` or `*.md` files. The latest artifacts are [here](https://github.com/bountonw/translate/actions/runs/7781611161). 

There are still many things that need/could be done to this PR yet:

- [x] Make the paths dynamic instead of hardcoded to PP1/PP01 #94
- [x] Remove the reference code headings in the output PDF #95 
- [x] Fix poetry #174
- [ ] Add content change timestamp #30

Nice to have when we get to it:

- [ ] Update the `metadata.yaml` to accurately reflect PP instead of MB data #93
- [ ] Figure out missing book name #96
- [ ] Improve the fonts for numerals and English text #97
- [ ] Maybe improve the output PDF names (instead of `PP01_th.pdf` maybe like `[Thai book name] - [chapter #] - [chapter name].pdf` or something) #98
- [ ] Customize the artifact name to be something better than `PP-${commit sha}` #100
- [ ] Only run the build process when needed (that is when files related to the PDFs, source or tooling, change) #101
- [ ] Reduce the dependencies needed by the makefile. Install time isn't terrible for something like this, but it might be possible to reduce the deps further. #102

### CODE REVIEW

**Comment by bountonw** [comment]
> * [ ]  Update the `metadata.yaml` to accurately reflect PP instead of MB data

Each chapter of PP, regardless of status, should be updated. This means all of the `.md` files in the multiple subdirectories of `th/PP`. The exported files should include which book they are from `short name: PP1` `long name: Patriarchs and Prophets Volume 1` and the status of the chapter, `raw` `currently editing`, `public` or some such designation. How do we do this? Do we have a `PP` level `.yaml` file, a book level `.yaml` file and then a status line of each yaml header in each chapter? (Or does the script know what the status is based on which folder it is in? That would be better.)

> * [ ]  Maybe improve the output PDF names (instead of `PP01_th.pdf` maybe like `[Thai book name] - [chapter #] - [chapter name].pdf` or something)

`[book code][chapter ##]_[language code][status]_[timestamp].pdf`

> * [ ]  Customize the artifact name to be something better than `PP-${commit sha}`

What about this? `PP_[YYYYMMDD_HHMMSS]`

> * [ ]  Only run the build process when needed (that is when files related to the PDFs, source or tooling, change)

@tonyquicktech can you work on figuring out how to do this?

> * [ ]  Reduce the dependencies needed by the makefile. Install time isn't terrible for something like this, but it might be possible to reduce the deps further.

**Comment by bountonw** [comment]
I have created issue #92 to help us sort out who will do what. There are nine "tasks" mentioned above. But creating individual issues, it will be easier to discuss, assign, and avoid duplicate work.

**Comment by bountonw** [comment]
Individual issues have been created. Those that have not been assigned or adopted are free to be adopted.

**Comment by bountonw** [comment]
@mattleff I don't get it. When I merged main don't other branch it is now showing over 400 files changed. Will I lose the file history of what is already on main? This branch is also showing that it is 9 commits behind main? How can that be when I just merged? Very confused.

**Comment by mattleff** [comment]
@bountonw Ok, I see now that #104 didn't preserve the commit history from main. So it was like you sent up new files (w/o history). Can you take off branch protection for this branch and I'll remove the latest commit and try to merge from main (thus preserving history)?

**Comment by bountonw** [comment]
@mattleff protection off

**Review by bountonw — APPROVED** [review]

**Comment by mattleff** [comment]
@bountonw I merged #176 in and when #178 is merged in this *should* be good to go. The only remaining critical item is the content edit timestamp (#30), and I can work on that after this is on main. If things look good to you I'll let you review and merge this PR (after #178) so that you can massage the commit message as you wish.

**Pull request merged**
