### PR TITLE
Add indd file for Thai MB

### PR DESCRIPTION
**Pull request by bountonw**
This file was originally named MB v 5.80 (World Paragraph Composer).indd and was finalized sometime in January 2023. However, we've opted to use a Christmas 2022 timestamp for this historical file. This version was not the one sent to the printers for the first edition; instead, it served as a working copy for generating sharable PDFs. It will also be the basis for a new typeset to align with updated source files and address issues in the current PDFs and print books.

### CODE REVIEW

**Comment by bountonw** [comment]
@mattleff This is ready to review.

**Comment by hsteck1844** [comment]
A little more info regarding this file: It is actually not the one that was used to generate the PDF for printing. That one was the MB_v5.80.indd, which used the Adobe Paragraph Composer, whereas this one is set to use the World-Ready Composer. I had learned more about the World-ready Composer after we had sent the PDF to the printing company, so **_I used this file to create the e-book versions of the book_**. Apologies for confusion. I pointed you to this file because it uses the World Ready Composer, which we should be using at this point. **_It may be wise to review the line breaks in the new inDesign before finalizing it_**.

For what it's worth, all files -- the one for printing and this one as well, were created in early January.

**Review by hsteck1844 — APPROVED** [review]
As noted in my comment, technically, this file was not the one used to generate the first printing master. It **_was_** used to generate the "e-book" PDFs from which text could be copied and pasted.

**Comment by bountonw** [comment]
@hsteck1844 

> As noted in my comment, technically, this file was not the one used to generate the first printing master. It **_was_** used to generate the "e-book" PDFs from which text could be copied and pasted.

I’ve updated the PR description. Does this look right to you?

**Review by mattleff — APPROVED** [review]

**Pull request merged**
