### PR TITLE
Lint to ensure that emphasis/strong use asterisks

### PR DESCRIPTION
**Pull request by mattleff**
From messaging discussion

### CODE REVIEW

**Review by bountonw — COMMENTED** [review]
I don't understand this and how it works. Should be **bold** *italcs*

**Comment by bountonw** [comment]
\*\*bold\*\* \*italics\*

**Comment by mattleff** [comment]
@bountonw This is linting to ensure that only `**bold**` or `*italic*` are used instead of `__bold__` or `_italic_`. I think that's what we want, right?

**Comment by bountonw** [comment]
> @bountonw This PR adds linting to ensure that only `**bold**` or `*italic*` are used instead of `__bold__` or `_italic_`. I think that's what we want, right?

Yes. This is what we want. I can't see how it works. But will accept.

**Review by bountonw — APPROVED** [review]

**Comment by mattleff** [comment]
@bountonw It uses a built-in lint rule from markdownlint documented here: https://github.com/DavidAnson/markdownlint/blob/main/doc/md049.md.

**Pull request merged**
