### PR TITLE
Add invalid_thai_words.txt file

### PR DESCRIPTION
**Pull request by bountonw**
This is list of common typos and misspellings in Thai.

### CODE REVIEW

**Comment by bountonw** [comment]
@mattleff This is in the wrong location, and might even have the wrong name. But it is a start. I don't know that any of these words are currently in the code base, but they are frequent misspellings and are easy to introduce. I also need a place to add new words to as I come across them. 

Feel free to rename and relocate (and even reformat) or tell me and I can do it.

**Review by mattleff — APPROVED** [review]
@bountonw I've redone this PR, so it's really you that should be reviewing it, but anyway, if it looks ok feel free to merge it. We now check for forbidden terms in public files.

**Comment by bountonw** [comment]
@mattleff So, if I want to add hundreds of words to this list, eventually, how do I do the json? Is it just one long line?

**Comment by mattleff** [comment]
> @mattleff So, if I want to add hundreds of words to this list, eventually, how do I do the json? Is it just one long line?

Ok, on second thought, it wasn't that much harder to use a plaintext file. See what you think of the latest commit which will allow just adding newline-separated terms in a plaintext/markdown file.

**Pull request merged**
