### PR TITLE
Add current LBF book PDF

### PR DESCRIPTION
**Pull request by mattleff**
@bountonw I wasn't sure if you wanted to add the PDFs with versioned names, so all versions are kept next to each other ([like MB](https://github.com/bountonw/MB_th/tree/main/Book%20PDF%20previews)), or (option 2) if we want to use generic names (i.e., `book.pdf`) and simply change the file in place over time. The latter option has two implications:

1. Checking out the repo would be smaller since only one PDF would need to be downloaded, rather than N-many.
2. To get, for example, the 9am May 19 PDF it would be necessary to go into the git history for the path (e.g., `book.pdf`) and find the version at a particular timestamp.

This PR is currently option 1 (like MB), but I would probably lean toward option 2 as long as everyone who needs to access the PDFs is comfortable viewing the git history of a file. It's pretty easy with GitHub, but it is less obvious and requires an additional step to compare two versions of the same file.

### CODE REVIEW

**Comment by bountonw** [comment]
I prefer version 1, but am willing to go with version 2 if there is a clear step-by-step protocol that is accessible and not buried. Like in the README.

**Comment by mattleff** [comment]
@bountonw That's fine. Let's do option 1. Do we want to define a naming scheme for the file names? Wdyt of using the timestamp, like `book_[yyyy.MM.dd_hh.mm].ext` (e.g., `book_2024.05.20_10.39.pdf`)? Or do you prefer using a version sequence like with MB?

**Comment by bountonw** [comment]
I am comfortable with option 1 or 2 or with either option for naming. I'll let you determine what is best. The only thing I ask for is clear instructions and consistency. (Or at least an attempt at consistency.) since we have PDFs and also the marked PDFs, we need a way of keeping both. Also there are sometimes more than one version of the same version (with highlights and without highlights etc.) we need a way to deal with that too.

**Comment by mattleff** [comment]
@bountonw Check out the changes on the PR now. I've tried to describe in the README what we're wanting, and I've added the two compare reports from Kenton as naming examples. Let me know what you think.

**Comment by bountonw** [comment]
When I was in 1st grade, the Music teacher came for the first day of children's choir and melodically sang her introduction, "My name is Mrs. Dorsey." She then pointed at me to introduce myself at which point I dutifully sand, "My name is Mrs. Dorsey" to the great pleasure of my classmates and general mortification to myself. 

Should `book` be `book` in the uploaded pdfs or should they be `LBF`?

**Comment by bountonw** [comment]
The sections of the file names are separated by `_` underscore. Should the spaces within the optional section be hyphens instead of underscores?

**Comment by mattleff** [comment]
@bountonw 🤣 ...so, will we ever have any other types of PDFs in these folders besides full books? If not, then, sure, let's use the book abbreviation for first filename segment.

**Comment by bountonw** [comment]
If we have LBF01-03_202406011013_font-test.pdf it is a division of the book. That way, if someone is working on typesetting more than one book (we have 5 books in the typesetting stage) we are not confused.

**Comment by mattleff** [comment]
@bountonw Sounds good. I've changed the PR accordingly.

**Review by bountonw — APPROVED** [review]

**Pull request merged**
