### PR TITLE
Add content last modified date to PDFs

### LINKED ISSUE #30: Versioning of .md translation files
We need a way to inform the public regarding what version of the document they are looking at. As public-facing documents are edited occasionally, how does the general public know if they have the latest version?

### PR DESCRIPTION
**Pull request by mattleff**
Fixes #30. The PDFs with content last modified dates are [here](https://github.com/bountonw/translate/actions/runs/8275674045).

### CODE REVIEW

**Review by bountonw — APPROVED** [review]
PDFs look good.

**Comment by bountonw** [comment]
> Fixes #30. The PDFs with content last modified dates are [here](https://github.com/bountonw/translate/actions/runs/8275674045).

You can merge when you are ready. Will "here" always be "here" or will that change at the next PR?

**Comment by mattleff** [comment]
@bountonw It will change with each PR. I want to setup automated GitHub releases so that we can have a place ([releases](https://github.com/bountonw/translate/releases)) to link people for now to where they can see the latest (and all previous versions) of the available PDFs.

**Comment by bountonw** [comment]
@mattleff Currently we are triggering a rebuild of everything at each commit. Since sometimes there are 65 commits when sorting through the spelling issues etc. Won't this get unwieldy? Or does each commit's rebuild overwrite the previous one, thus leaving only 1 rebuild per PR?  I try to do daily translation PRs on the files I am working on. Currently they trigger entire rebuilds.

**Comment by mattleff** [comment]
> @mattleff Currently we are triggering a rebuild of everything at each commit. Since sometimes there are 65 commits when sorting through the spelling issues etc. Won't this get unwieldy? Or does each commit's rebuild overwrite the previous one, thus leaving only 1 rebuild per PR? I try to do daily translation PRs on the files I am working on. Currently they trigger entire rebuilds.

@bountonw Yes, I was thinking to only generate releases on merges to main. So if there were 3 PRs into main in a day that would generate 3 release entries on the Releases page. We could make it more infrequent (like maybe on a [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule), e.g. every night if there are changes) or even possibly manual (but I lean against things that we have to remember to do). The PDFs themselves need to be rebuilt on each commit so we can confirm that things look as they should, but the release can be more infrequent and/or intentional.

**Comment by bountonw** [comment]
ok

**Pull request merged**
