### PR TITLE
Add thin space around italics

### PR DESCRIPTION
**Pull request by mattleff**
Refs #268

### CODE REVIEW

**Comment by mattleff** [comment]
@kenton-r Can you check the thin space on the ICMLs [here](https://github.com/bountonw/translate/actions/runs/9057346004?pr=285) and make sure I did the right thing?

**Comment by kenton-r** [comment]
I made a mistake and used the thin space. The thin space is too wide.

Italic_thin_01

This is what is looks like with "hair" spaces on both sides.

Italic_thin_02

However, this word is at the end of a sentence. Can we check to see if there is a following space before adding the "hair" space at the end. (Maybe we need to check at the beginning too).

Italic_thin_03

This is the "hair" space character: " "

**Comment by mattleff** [comment]
@kenton-r [Here](https://github.com/bountonw/translate/actions/runs/9076982904?pr=285) are the ICMLs with the duplicate spaces removed. Let me know if this looks good to you.

**Comment by kenton-r** [comment]
It is still putting a hair space when there is a full space afterwards. Is this what you mean by "the duplicate spaces removed"

**Comment by bountonw** [comment]
It shouldn't add a thin space if there is already a regular space.

**Comment by mattleff** [comment]
@kenton-r Yeah, it shouldn't be doing that. Checking...

**Comment by mattleff** [comment]
@kenton-r Try these files. Apparently the hair space is not a space according to Lua. 😆

**Pull request merged**
