### PR TITLE
Lint for invalid spacing

### LINKED ISSUE #237: Lint for (ดู[^ ]
There should be a space after ดู when it is the first word after an opening parenthesis. I think the regex is `(ดู[^ ]`. This applies to the Thai files. It occurs in MB once. There may be some exceptions, but we can deal with them if and when they arise. So far we are running into cases where there should be a space.

### PR DESCRIPTION
**Pull request by mattleff**
Fixes #237

### CODE REVIEW

**Comment by mattleff** [comment]
@bountonw Let me know if these all look like valid catches and I can fix them.

**Comment by bountonw** [comment]
> @bountonw Let me know if these all look like valid catches and I can fix them.

@mattleff I think we should exclude the raw files for this one as there are several caught that shouldn't be caught. For those that are not in the raw folders, a space can be added after `(ดู`

**Comment by bountonw** [comment]
@mattleff Or you could just add a space to all of them. That would probably be easier. We can deal with the raw files when we edit them as those (marks/suggestions) are places that are flagged for me to edit anyway.

**Comment by mattleff** [comment]
@bountonw I've pushed a commit to fix all the spaces.

**Review by bountonw — APPROVED** [review]

**Pull request merged**
