### PR TITLE
Attempt to workaround forbidden word breaks bug

### PR DESCRIPTION
**Pull request by mattleff**
Refs #268.

### CODE REVIEW

**Comment by mattleff** [comment]
@kenton-r Try [these ICMLs](https://github.com/bountonw/translate/actions/runs/9146626320?pr=289) and let me know how things look.

**Comment by kenton-r** [comment]
So for what I have examined this work-around is working with the forbidden break words. 
However there is now a conflict with the three dots for the ellipse. There are three unrecognized characters.
three mysterious characters

**Comment by mattleff** [comment]
[LBF.zip](https://github.com/bountonw/translate/files/15383093/LBF.zip)

@kenton-r Try these files.

**Comment by mattleff** [comment]
@kenton-r Let me know how those look and I'll work on finishing up this PR.

**Comment by kenton-r** [comment]
Yes, this is working good. I think that we are ready to finalize the automation work on this and start the manual work. Let me know when the final ICML files are created.

**Review by bountonw — APPROVED** [review]

**Comment by mattleff** [comment]
@kenton-r You can grab the latest ICMLs from [here](https://github.com/bountonw/translate/actions/runs/9183847814). I think that's all the changes I know of.

**Pull request merged**
