### PR TITLE
Rename text files to md and update formatting

### LINKED ISSUE #19: Compare appendix note 3 in PP25.md with PP25_AN3.md
Two locations of the same content. Need to merge and delete the text at the bottom of PP25, leaving PP25_AN3.md. Resolve conflicts before deleting. This should be done after #14 .

### PR DESCRIPTION
**Pull request by bountonw**
* Add missing space before paragraph tags
* Removing trailing white space
* Remove end of file blank lines
* Promote paragraphs to level 2 heading 
* Demote subheadings to level 3 and nest under paragraphs
* Fix improper tags and line spacing
* Fix typos stumbled across
* Translate missing paragraphs 607.3 in PP59.md #13 
* Resolve #19 conflict of two locations for Appendix Note 3

### CODE REVIEW

**Comment by bountonw** [comment]
@mattleff 

Can you help with removing the double spaces in these files? I am unable to do it without touching the yaml.

**Comment by mattleff** [comment]
@bountonw I've pushed two commits just now. The first removes all the non-leading double spaces from the .md files. The second changes the validate-md.sh to only error on non-leading double spaces. The issue is that we're currently using quadruple spaces for quotes, so we get errors with the previous code. Eventually we might consider using another symbol for quotes (such as `> `, which is standard for [commonmark](https://commonmark.org/help/) blockquotes), but for now it's easier just to search for non-leading double spaces. Let me know if you want to go another direction on that.

**Comment by bountonw** [comment]
Thank you. I think for exporting to other formats using spaces you be easier. These "poetry" sections are not well formulate yet. But that is another issue. I'll take a quick look at the files here and merge.

**Comment by bountonw** [comment]
@mattleff can we have the update to the validate script as a separate pull request?

**Comment by mattleff** [comment]
@bountonw Sure, I've broken it out to #15 and removed that commit from this branch.

**Comment by bountonw** [comment]
@mattleff I merged pull request #15. In reviewing the changes files I noticed an issue regarding nesting of ### level headings.

Also there are some validation issues to work out. I will look at the nested subheadings tomorrow morning. Can you look at the validation issues?

**Comment by bountonw** [comment]
@mattleff 

I have reviewed all of the files. 

Issue #20 is failing the validation tests. I think that is the only thing remaining in this PR.

**Comment by bountonw** [comment]
@mattleff The checks are still failing.

**Comment by bountonw** [comment]
@mattleff I think I have resolved any translation issues that I want to deal with at this import phase. This branch has the latest version of everything. The sooner it can be merged to main, the easier it will be for editing purposes. Friday I will be driving to Bangkok, but will have access to the github app on my phone. Then Sunday afternoon I should be free in the hotel if there is anything  for me to do on this.

**Comment by mattleff** [comment]
@bountonw I've merged master to this branch to get #22, and I've pushed another commit fixing a duplicate space. That leaves the following issues (obtained by commenting the `exit 1`s in validate-md.sh to see all the errors rather than just the first one):

```
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP69.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP59.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP68.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP63.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP73.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP67.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP59_AN9.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP66.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP59_AN8.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP62.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP72.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP65.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP61.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP71.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP60.md
Closing parenthesis not properly followed in th/PP/PP5/01_raw/PP64.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP49.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP58.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP48.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP57.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP47.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP53.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP52.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP56.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP51.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP55.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP54.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP44.md
Closing parenthesis not properly followed in th/PP/PP4/01_raw/PP50.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP38.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP39.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP32.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP36.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP43.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP37.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP32_AN7.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP42.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP33.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP34.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP41.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP30.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP31.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP35.md
Closing parenthesis not properly followed in th/PP/PP3/01_raw/PP40.md
```

It appears that there are lots of cases where there are parentheses in the content that are placeholders for future finished translation (such as [here](https://github.com/bountonw/translate/pull/14/files#diff-475331cf798f63e99e111cc20a33ba4fe5552487324a604f1e7a67408bc21c20R97), "... ความสว่างได้ฉายออกจากไม้กางเขนแห่งเนินเขา(คาลวารี)และจากสถานบริสุทธิ์ต่างๆ ..."). How do we want to handle those situations?

**Comment by bountonw** [comment]
Ah, yes indeed. So we should disable this for edit and raw directories and only use this for the public directories.

**Comment by bountonw** [comment]
@mattleff I have reviewed all changed files since list review. We need to update the validation script to only search `.md` files in `03_public` subdirectories. Then we should be able to merge. Now the validation is blocking merging.

**Comment by bountonw** [comment]
Why is this still failing?

**Pull request merged**
